package com.example.demo.entity.task_genres;

import java.util.Date;

public class TaskGenre {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_genres.task_genre_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer taskGenreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_genres.genre_name
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private String genreName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_genres.created_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_genres.created_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_genres.updated_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_genres.updated_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_genres.task_genre_id
     *
     * @return the value of task_genres.task_genre_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getTaskGenreId() {
        return taskGenreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_genres.task_genre_id
     *
     * @param taskGenreId the value for task_genres.task_genre_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setTaskGenreId(Integer taskGenreId) {
        this.taskGenreId = taskGenreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_genres.genre_name
     *
     * @return the value of task_genres.genre_name
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public String getGenreName() {
        return genreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_genres.genre_name
     *
     * @param genreName the value for task_genres.genre_name
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setGenreName(String genreName) {
        this.genreName = genreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_genres.created_by
     *
     * @return the value of task_genres.created_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_genres.created_by
     *
     * @param createdBy the value for task_genres.created_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_genres.created_at
     *
     * @return the value of task_genres.created_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_genres.created_at
     *
     * @param createdAt the value for task_genres.created_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_genres.updated_by
     *
     * @return the value of task_genres.updated_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_genres.updated_by
     *
     * @param updatedBy the value for task_genres.updated_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_genres.updated_at
     *
     * @return the value of task_genres.updated_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_genres.updated_at
     *
     * @param updatedAt the value for task_genres.updated_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}