package com.example.demo.entity.tasks;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.task_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.user_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.title
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.description
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.status_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.genre_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer genreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.due_date
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Date dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.created_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.created_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.updated_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.updated_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.task_id
     *
     * @return the value of tasks.task_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.task_id
     *
     * @param taskId the value for tasks.task_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.user_id
     *
     * @return the value of tasks.user_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.user_id
     *
     * @param userId the value for tasks.user_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.title
     *
     * @return the value of tasks.title
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.title
     *
     * @param title the value for tasks.title
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.description
     *
     * @return the value of tasks.description
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.description
     *
     * @param description the value for tasks.description
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.status_id
     *
     * @return the value of tasks.status_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.status_id
     *
     * @param statusId the value for tasks.status_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.genre_id
     *
     * @return the value of tasks.genre_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getGenreId() {
        return genreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.genre_id
     *
     * @param genreId the value for tasks.genre_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setGenreId(Integer genreId) {
        this.genreId = genreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.due_date
     *
     * @return the value of tasks.due_date
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.due_date
     *
     * @param dueDate the value for tasks.due_date
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.created_by
     *
     * @return the value of tasks.created_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.created_by
     *
     * @param createdBy the value for tasks.created_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.created_at
     *
     * @return the value of tasks.created_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.created_at
     *
     * @param createdAt the value for tasks.created_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.updated_by
     *
     * @return the value of tasks.updated_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.updated_by
     *
     * @param updatedBy the value for tasks.updated_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.updated_at
     *
     * @return the value of tasks.updated_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.updated_at
     *
     * @param updatedAt the value for tasks.updated_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}