package com.example.demo.repository.mapper.tasks;

import com.example.demo.entity.tasks.Task;
import com.example.demo.entity.tasks.TaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    long countByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int insert(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int insertSelective(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    Task selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByExampleSelective(@Param("row") Task row, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByExample(@Param("row") Task row, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByPrimaryKeySelective(Task row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByPrimaryKey(Task row);
}