package com.example.demo.entity.task_status;

import java.util.Date;

public class TaskStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_status.task_status_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer taskStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_status.status_name
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private String statusName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_status.created_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_status.created_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_status.updated_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Integer updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_status.updated_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_status.task_status_id
     *
     * @return the value of task_status.task_status_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getTaskStatusId() {
        return taskStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_status.task_status_id
     *
     * @param taskStatusId the value for task_status.task_status_id
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setTaskStatusId(Integer taskStatusId) {
        this.taskStatusId = taskStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_status.status_name
     *
     * @return the value of task_status.status_name
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_status.status_name
     *
     * @param statusName the value for task_status.status_name
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_status.created_by
     *
     * @return the value of task_status.created_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_status.created_by
     *
     * @param createdBy the value for task_status.created_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_status.created_at
     *
     * @return the value of task_status.created_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_status.created_at
     *
     * @param createdAt the value for task_status.created_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_status.updated_by
     *
     * @return the value of task_status.updated_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_status.updated_by
     *
     * @param updatedBy the value for task_status.updated_by
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_status.updated_at
     *
     * @return the value of task_status.updated_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_status.updated_at
     *
     * @param updatedAt the value for task_status.updated_at
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}