package com.example.demo.repository.mapper.task_status;

import com.example.demo.entity.task_status.TaskStatus;
import com.example.demo.entity.task_status.TaskStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    long countByExample(TaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int deleteByExample(TaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int deleteByPrimaryKey(Integer taskStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int insert(TaskStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int insertSelective(TaskStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    List<TaskStatus> selectByExample(TaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    TaskStatus selectByPrimaryKey(Integer taskStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByExampleSelective(@Param("row") TaskStatus row, @Param("example") TaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByExample(@Param("row") TaskStatus row, @Param("example") TaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByPrimaryKeySelective(TaskStatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByPrimaryKey(TaskStatus row);
}