package com.example.demo.repository.mapper.task_genres;

import com.example.demo.entity.task_genres.TaskGenre;
import com.example.demo.entity.task_genres.TaskGenreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskGenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    long countByExample(TaskGenreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int deleteByExample(TaskGenreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int deleteByPrimaryKey(Integer taskGenreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int insert(TaskGenre row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int insertSelective(TaskGenre row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    List<TaskGenre> selectByExample(TaskGenreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    TaskGenre selectByPrimaryKey(Integer taskGenreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByExampleSelective(@Param("row") TaskGenre row, @Param("example") TaskGenreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByExample(@Param("row") TaskGenre row, @Param("example") TaskGenreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByPrimaryKeySelective(TaskGenre row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_genres
     *
     * @mbg.generated Sat Apr 18 20:02:57 JST 2026
     */
    int updateByPrimaryKey(TaskGenre row);
}